### ISSUE TITLE
Which way?

### ISSUE THREAD

**Issue by n251ea** [apps4av/avarex#25]
the own ship image needs to be made smaller, the size used it too large and can result in unintended consequences.  See the attached image, based upon the image alone I don't know if I'm traveling east or west.  The ownship image needs to be smaller and more defined showing which direction is being traveled.

![yzK8nf9l1B6Weh6q](https://github.com/user-attachments/assets/50618665-4683-4fc6-ae85-2291c07d8d5c)

**Comment by apps4av** [comment]
fixed
