### ISSUE TITLE
Traffic symbols are oriented relative to north up

### ISSUE THREAD

**Issue by n251ea** [apps4av/avarex#6]
Regardless of if the map is set to track up or north up the traffic symbols are orientated as if the map is north up.  The traffic symbols do move correctly but can appear to be morning sideways when set to track up

**Comment by shanelenagh** [comment]
Working on this now @apps4av

**Comment by shanelenagh** [comment]
Did some testing on a fix Friday, but not done yet (the rest of the weekend was quite busy with family and external commitments).  I am still working on it, though.

**Comment by shanelenagh** [comment]
I think Zubair may have fixed this in commit a48d03b9 (I haven't tested, but it was similar to what I was doing, though I was doing in inside the existing rotation in traffic_cache, just passing the north boolean in), as I just noticed the conflict with my change when I pulled the latest from upstream master.  Sorry, @apps4av , family and work have been keeping me occupied this past week, so it looks like you beat me to it.   I'll look at the audible toggle, if that isn't done yet too.

**Comment by shanelenagh** [comment]
Hah, I see you have the audible toggle too, in commit c863dc3c58a618b0f60d68d2171f663b02935167 that I just saw in another pull I did since I typed that last message.  You are too good, sir (and I am too slow/busy).  Sorry about that.

**Comment by apps4av** [comment]
Oh sorry :). Yes it's working ok with rotation. And I added concept for
audible alert mute. Long press on any traffic icon to get a callback and do
something with it. However toggling of audible alerts in setting has no
effect on audible alerts. So I will leave it at that for your fix and icons
change instead of a big cross icon.

**Comment by apps4av** [comment]
I am very bored. Feel free to blackout anything I did.

**Comment by shanelenagh** [comment]
No worries, sir.  I am glad you did that audible alerts toggle change (which I will build off, probably just tweaking the icon and look, which I will run by you), as know I finally understand what you were talking about with the tooltip--just couldn't picture it before.  And I feel bad about not really getting to sit down and look at these until tonight.  I watch the forums and I know feedback on the beta is coming in hot and heavy, so I don't fault you for slamming it out; I will try to be a better help going forward.  Aside from the toggle UI tweaking, I know Jeff R has some feedback on other traffic items, but I will probably paste them into tickets like this so they can get more review from you and others before diving too deep (I'm sure you talk to him regularly, though).

And happy early Father's Day. :-)

**Comment by apps4av** [comment]
Fixed in build 14
